Readme updates
TaskarCenterAtUW/TDEI-file-service pull request #36
Opened 2023-05-31 09:39 UTC by MashB

Readme updated based on review feedback

2023-05-31 11:04 UTC, susrisha commented on README.md
> +Secrets are configured as an environment variables on the deployment server.
Remove `an` .
Secrets are configure as environment variables on the deployment server.

2023-05-31 11:04 UTC, susrisha requested changes
One minor change

2023-05-31 11:57 UTC, rdevalap approved these changes, later dismissed

2023-05-31 12:53 UTC, rdevalap approved these changes

2023-06-01 04:25 UTC, susrisha approved these changes

2023-06-01 07:16 UTC, merged